version: "3.9"
services:
  auth:
    build:
      context: ./service_auth
      dockerfile: Dockerfile
    depends_on: 
      - postgres
    links:
      - postgres
    env_file: variables.env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8080:8080"
  postgres:
    image: postgres:14.3-alpine
    env_file: variables.env
    ports:
      - "5432:5432"
    volumes:
      - ./db-templates:/docker-entrypoint-initdb.d
